spring:
  application:
    name: product-api

  liquibase:
    change-log: db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver